### ISSUE TITLE
Please remove "Additional json" and "Windows drivers" steps

### ISSUE THREAD

**Issue by facchinm** [bcmi-labs/arduino-pro-content#11]
from https://github.com/bcmi-labs/arduino-pro-content/blob/master/content/tutorials/portenta-h7/por-ard-gs/content.md :wink: 

The steps should be obsolete by the time people get their boards (and the zadig one is also a bit risky)

**Comment by sbhklr** [comment]
Great if we can get rid of this! Thanks for the update @facchinm. @i-herrera Can you test this with the new core version and make a Pull Request to remove the obsolete content?

**Comment by sbhklr** [comment]
Done.
