### ISSUE TITLE
Add simplified boot command to tutorial

### ISSUE THREAD

**Issue by sbhklr** [bcmi-labs/arduino-pro-content#18]
In the dual core example we shall rename the force boot command to `bootM4()` once my PR made it into a new release of the core. SEE: https://github.com/arduino/ArduinoCore-mbed/pull/23

**Comment by Lenardgeorge** [comment]
This was tested by @i-herrera and it worked on the new boards.

**Comment by sbhklr** [comment]
@Lenardgeorge This issue is about updating the tutorial. The changes haven't been made in the content.

**Comment by sbhklr** [comment]
Done.
